#!/usr/bin/env bash
# shellcheck disable=SC1091

set -euo pipefail
cd "$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )/.."
. 'script/utils.sh'
. 'script/import.sh'

update_homebrew() {
    h1 'Homebrew'
    if command -v brew; then
        h2 'Update Homebrew'
        run brew update
        run brew cleanup
    else
        h2 'Install Homebrew'
        /usr/bin/env bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install.sh)"
    fi

    h2 'Update Homebrew formulas'
    run brew bundle
}

case "$(uname)" in
    Darwin*)
        update_homebrew
        ;;
    Linux*)
        if command -v apt-get; then
            # Debian or Ubuntu
            sudo apt-get install build-essential procps curl file git python3 python3-pip libffi-dev
        elif command -v yum; then
            # Fedora, CentOS, or Red Hat
            sudo yum groupinstall 'Development Tools'
            sudo yum install procps-ng curl file git
            sudo yum install libxcrypt-compat # needed by Fedora 30 and up
        fi
        update_homebrew
        ;;
    CYGWIN*)
        exit_failure 'Windows is not currently supported'
        ;;
esac
