#!/usr/bin/env bash
# shellcheck disable=SC1091

set -euo pipefail
cd "$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )/.."
. 'script/utils.sh'
. 'script/import.sh'

config_path="../plex-config/plex-meta-manager/config.yml"

pipenv run python plex_meta_manager.py --config "$config_path" --run --debug --trace --width '140'
