#!/usr/bin/env bash
# shellcheck disable=SC1091

set -euo pipefail
cd "$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )/.."
. 'script/utils.sh'
. 'script/import.sh'

h1 'pyenv'

python_version=$(cat .python-version)

h2 "Install Python version $python_version"
run pyenv install --skip-existing "$python_version"
